version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./../app/pcheliki.monolit:/var/www
    ports:
      - "8078:80"
    container_name: nginx_con
    depends_on: [php]

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./../app/pcheliki.monolit:/var/www
    container_name: php_con

  #Tyt baza

  node:
    build:
      context: .
      dockerfile: node/Dockerfile
    volumes:
      - ./../app/pcheliki.monolit:/var/www
    working_dir: /var/www
    command: npm run build
    container_name: node_con
    depends_on: [ php ]
